#!/usr/bin/env bash

# This file is part of The RetroPie Project
#
# The RetroPie Project is the legal property of its developers, whose names are
# too numerous to list here. Please refer to the COPYRIGHT.md file distributed with this source.
#
# See the LICENSE.md file at the top-level directory of this distribution and
# at https://raw.githubusercontent.com/RetroPie/RetroPie-Setup/master/LICENSE.md
#

rp_module_id="scratch2"
rp_module_desc="Scratch 2 Offline Editor"
rp_module_licence="GPLv2 https://raw.githubusercontent.com/LLK/scratch-flash/develop/COPYING"
rp_module_section="exp"
rp_module_flags="!mali !x86"

function depends_scratch2() {
        getDepends git  matchbox xorg
}

function sources_chromium() {
    apt-get install scratch2
}

function configure_scratch2() {
    mkRomDir "ports"
    mkdir -p "$md_inst"
    moveConfigDir "$home/.config/$md_id" "$md_conf_root/$md_id"
    cat >"$md_inst/scratch2.sh" << _EOF_
#!/bin/bash
xset -dpms s off s noblank
matchbox-window-manager -use_titlebar yes &
/usr/bin/scratch2
_EOF_
    chmod +x "$md_inst/scratch2.sh"

    addPort "$md_id" "scratch2" "Scratch 2 Offline Editor" "xinit $md_inst/scratch2.sh"
}
